// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using assignment3.Data;

#nullable disable

namespace assignment3.Migrations
{
    [DbContext(typeof(AarhusSpaceContext))]
    partial class AarhusSpaceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AstronautMission", b =>
                {
                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("MissionId", "StaffId");

                    b.HasIndex("StaffId");

                    b.ToTable("AstronautMission");

                    b.HasData(
                        new
                        {
                            MissionId = 1,
                            StaffId = 201
                        },
                        new
                        {
                            MissionId = 1,
                            StaffId = 202
                        },
                        new
                        {
                            MissionId = 1,
                            StaffId = 203
                        },
                        new
                        {
                            MissionId = 1,
                            StaffId = 204
                        },
                        new
                        {
                            MissionId = 1,
                            StaffId = 205
                        },
                        new
                        {
                            MissionId = 2,
                            StaffId = 202
                        },
                        new
                        {
                            MissionId = 2,
                            StaffId = 203
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ScientistMission", b =>
                {
                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("MissionId", "StaffId");

                    b.HasIndex("StaffId");

                    b.ToTable("ScientistMission");

                    b.HasData(
                        new
                        {
                            MissionId = 1,
                            StaffId = 101
                        },
                        new
                        {
                            MissionId = 1,
                            StaffId = 102
                        },
                        new
                        {
                            MissionId = 2,
                            StaffId = 101
                        },
                        new
                        {
                            MissionId = 2,
                            StaffId = 102
                        },
                        new
                        {
                            MissionId = 2,
                            StaffId = 103
                        });
                });

            modelBuilder.Entity("assignment3.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("assignment3.Entities.Astronaut", b =>
                {
                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<float>("ExperienceSim")
                        .HasColumnType("real");

                    b.Property<float>("ExperienceSpace")
                        .HasColumnType("real");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffId");

                    b.ToTable("Astronauts");

                    b.HasData(
                        new
                        {
                            StaffId = 201,
                            ExperienceSim = 4800f,
                            ExperienceSpace = 4300f,
                            Rank = "Pilot"
                        },
                        new
                        {
                            StaffId = 202,
                            ExperienceSim = 7200f,
                            ExperienceSpace = 8600f,
                            Rank = "Commander"
                        },
                        new
                        {
                            StaffId = 203,
                            ExperienceSim = 8500f,
                            ExperienceSpace = 10500f,
                            Rank = "Commander"
                        },
                        new
                        {
                            StaffId = 204,
                            ExperienceSim = 1500f,
                            ExperienceSpace = 0f,
                            Rank = "Astronaut Candidate"
                        },
                        new
                        {
                            StaffId = 205,
                            ExperienceSim = 3200f,
                            ExperienceSpace = 4100f,
                            Rank = "Mission Specialt"
                        });
                });

            modelBuilder.Entity("assignment3.Entities.CelestialBody", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BodyType")
                        .HasColumnType("int");

                    b.Property<float>("Dist")
                        .HasColumnType("real");

                    b.Property<string>("ParentPlanetName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.HasIndex("ParentPlanetName");

                    b.ToTable("Bodies");

                    b.HasData(
                        new
                        {
                            Name = "Earth",
                            BodyType = 0,
                            Dist = 1f
                        },
                        new
                        {
                            Name = "Jupiter",
                            BodyType = 1,
                            Dist = 5.2f
                        },
                        new
                        {
                            Name = "Lunar",
                            BodyType = 3,
                            Dist = 1.002f,
                            ParentPlanetName = "Earth"
                        },
                        new
                        {
                            Name = "Europa",
                            BodyType = 3,
                            Dist = 5.201f,
                            ParentPlanetName = "Jupiter"
                        });
                });

            modelBuilder.Entity("assignment3.Entities.Experiment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeadScientistId")
                        .HasColumnType("int");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeadScientistId");

                    b.HasIndex("MissionId");

                    b.ToTable("Experiments");
                });

            modelBuilder.Entity("assignment3.Entities.LaunchPad", b =>
                {
                    b.Property<string>("LocationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("LaunchPads");

                    b.HasData(
                        new
                        {
                            LocationId = "Pad-Alpha",
                            MaxWeight = 1000000,
                            Status = "Active"
                        },
                        new
                        {
                            LocationId = "Pad-Beta",
                            MaxWeight = 800000,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("assignment3.Entities.Manager", b =>
                {
                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffId");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            StaffId = 1,
                            Department = "Ground Support"
                        },
                        new
                        {
                            StaffId = 2,
                            Department = "Flight Ops"
                        });
                });

            modelBuilder.Entity("assignment3.Entities.Mission", b =>
                {
                    b.Property<int>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MissionId"));

                    b.Property<string>("CelestialDest")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Duration")
                        .HasColumnType("real");

                    b.Property<DateTime>("LaunchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LaunchLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RocketId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("MissionId");

                    b.HasIndex("CelestialDest");

                    b.HasIndex("LaunchLocation");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RocketId")
                        .IsUnique()
                        .HasFilter("[RocketId] IS NOT NULL");

                    b.ToTable("Missions");

                    b.HasData(
                        new
                        {
                            MissionId = 1,
                            CelestialDest = "Lunar",
                            Duration = 27f,
                            LaunchDate = new DateTime(2034, 3, 16, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchLocation = "Pad-Beta",
                            ManagerId = 2,
                            Name = "Mission X",
                            RocketId = "SN-01",
                            Status = 3,
                            Type = 1
                        },
                        new
                        {
                            MissionId = 2,
                            CelestialDest = "Jupiter",
                            Duration = 14.5f,
                            LaunchDate = new DateTime(2045, 7, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchLocation = "Pad-Alpha",
                            ManagerId = 1,
                            Name = "Apollo 11",
                            RocketId = "SN-02",
                            Status = 3,
                            Type = 2
                        });
                });

            modelBuilder.Entity("assignment3.Entities.Rocket", b =>
                {
                    b.Property<string>("RocketId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CrewCap")
                        .HasColumnType("int");

                    b.Property<int>("FuelCap")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Payload")
                        .HasColumnType("int");

                    b.Property<int>("Stages")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("RocketId");

                    b.ToTable("Rockets");

                    b.HasData(
                        new
                        {
                            RocketId = "SN-01",
                            CrewCap = 5,
                            FuelCap = 4800000,
                            Name = "Falcon-X",
                            Payload = 140000,
                            Stages = 2,
                            Weight = 5000000f
                        },
                        new
                        {
                            RocketId = "SN-02",
                            CrewCap = 3,
                            FuelCap = 2100000,
                            Name = "Saturn-V",
                            Payload = 130000,
                            Stages = 3,
                            Weight = 2800000f
                        });
                });

            modelBuilder.Entity("assignment3.Entities.Scientist", b =>
                {
                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffId");

                    b.ToTable("Scientists");

                    b.HasData(
                        new
                        {
                            StaffId = 101,
                            Speciality = "Biology",
                            Title = "Phd"
                        },
                        new
                        {
                            StaffId = 102,
                            Speciality = "Physics",
                            Title = "Dr"
                        },
                        new
                        {
                            StaffId = 103,
                            Speciality = "Astronomy",
                            Title = "Proffesor"
                        });
                });

            modelBuilder.Entity("assignment3.Entities.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PayGrade")
                        .HasColumnType("int");

                    b.HasKey("StaffId");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            StaffId = 1,
                            HireDate = new DateTime(2016, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rachel Adams",
                            PayGrade = 2
                        },
                        new
                        {
                            StaffId = 2,
                            HireDate = new DateTime(2010, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jane Smith",
                            PayGrade = 4
                        },
                        new
                        {
                            StaffId = 101,
                            HireDate = new DateTime(2020, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jessica Day",
                            PayGrade = 5
                        },
                        new
                        {
                            StaffId = 102,
                            HireDate = new DateTime(2018, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nick Miller",
                            PayGrade = 6
                        },
                        new
                        {
                            StaffId = 103,
                            HireDate = new DateTime(2012, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ali Hazelwood",
                            PayGrade = 7
                        },
                        new
                        {
                            StaffId = 201,
                            HireDate = new DateTime(2016, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rick Roll",
                            PayGrade = 8
                        },
                        new
                        {
                            StaffId = 202,
                            HireDate = new DateTime(2011, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Amanda Smith",
                            PayGrade = 9
                        },
                        new
                        {
                            StaffId = 203,
                            HireDate = new DateTime(2009, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Damon Salvatore",
                            PayGrade = 9
                        },
                        new
                        {
                            StaffId = 204,
                            HireDate = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bella Hadid",
                            PayGrade = 7
                        },
                        new
                        {
                            StaffId = 205,
                            HireDate = new DateTime(2020, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bridget Mendler",
                            PayGrade = 8
                        });
                });

            modelBuilder.Entity("AstronautMission", b =>
                {
                    b.HasOne("assignment3.Entities.Mission", null)
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("assignment3.Entities.Astronaut", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("assignment3.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("assignment3.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("assignment3.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("assignment3.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScientistMission", b =>
                {
                    b.HasOne("assignment3.Entities.Mission", null)
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("assignment3.Entities.Scientist", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("assignment3.Entities.Astronaut", b =>
                {
                    b.HasOne("assignment3.Entities.Staff", "Staff")
                        .WithOne("AstonautDetails")
                        .HasForeignKey("assignment3.Entities.Astronaut", "StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("assignment3.Entities.CelestialBody", b =>
                {
                    b.HasOne("assignment3.Entities.CelestialBody", "ParentPlanet")
                        .WithMany("Moons")
                        .HasForeignKey("ParentPlanetName")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentPlanet");
                });

            modelBuilder.Entity("assignment3.Entities.Experiment", b =>
                {
                    b.HasOne("assignment3.Entities.Scientist", "LeadScientist")
                        .WithMany()
                        .HasForeignKey("LeadScientistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("assignment3.Entities.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeadScientist");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("assignment3.Entities.Manager", b =>
                {
                    b.HasOne("assignment3.Entities.Staff", "Staff")
                        .WithOne("ManagerDetails")
                        .HasForeignKey("assignment3.Entities.Manager", "StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("assignment3.Entities.Mission", b =>
                {
                    b.HasOne("assignment3.Entities.CelestialBody", "CelestialBody")
                        .WithMany("TargetMissions")
                        .HasForeignKey("CelestialDest")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("assignment3.Entities.LaunchPad", "LaunchPad")
                        .WithMany("MissionDetails")
                        .HasForeignKey("LaunchLocation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("assignment3.Entities.Manager", "ManagedBy")
                        .WithMany("ManageMission")
                        .HasForeignKey("ManagerId");

                    b.HasOne("assignment3.Entities.Rocket", "Rocket")
                        .WithOne("RocketUsed")
                        .HasForeignKey("assignment3.Entities.Mission", "RocketId");

                    b.Navigation("CelestialBody");

                    b.Navigation("LaunchPad");

                    b.Navigation("ManagedBy");

                    b.Navigation("Rocket");
                });

            modelBuilder.Entity("assignment3.Entities.Scientist", b =>
                {
                    b.HasOne("assignment3.Entities.Staff", "Staff")
                        .WithOne("ScientistDetails")
                        .HasForeignKey("assignment3.Entities.Scientist", "StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("assignment3.Entities.CelestialBody", b =>
                {
                    b.Navigation("Moons");

                    b.Navigation("TargetMissions");
                });

            modelBuilder.Entity("assignment3.Entities.LaunchPad", b =>
                {
                    b.Navigation("MissionDetails");
                });

            modelBuilder.Entity("assignment3.Entities.Manager", b =>
                {
                    b.Navigation("ManageMission");
                });

            modelBuilder.Entity("assignment3.Entities.Rocket", b =>
                {
                    b.Navigation("RocketUsed")
                        .IsRequired();
                });

            modelBuilder.Entity("assignment3.Entities.Staff", b =>
                {
                    b.Navigation("AstonautDetails");

                    b.Navigation("ManagerDetails");

                    b.Navigation("ScientistDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
