using System.ComponentModel.DataAnnotations;

namespace assignment3.DTO;

public class LaunchPadDTO
{
    public string LocationId {get; set;} = null!; 
    public string Status {get; set;} = "Active"; 
    public int MaxWeight {get; set;}

    // List of Mission IDs associated with this pad
    public List<int> MissionIds { get; set; } = new();
}

// THE CREATE DTO (Used for POST)
// The user MUST provide the LocationId here because it's a string.
public class LaunchPadCreateDTO
{
    // LocationId is required here because string PKs are not auto-generated by the DB.
    [Required]
    public string LocationId { get; set; } = null!;
    
    public string Status { get; set; } = "Active";
    
    // Declarative validation ensures data integrity before reaching the database.
    [Range(0, int.MaxValue, ErrorMessage = "Weight capacity cannot be negative.")]
    public int MaxWeight { get; set; }
}

// THE UPDATE DTO (Used for PUT)
// No LocationId! We don't let them change the Primary Key.
public class LaunchPadUpdateDTO
{
    public string Status { get; set; } = "Active";

    [Range(0, int.MaxValue, ErrorMessage = "Weight capacity cannot be negative.")]
    public int MaxWeight { get; set; }
}